# Generated by Django 6.0.2 on 2026-02-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_address_email_alter_address_is_default_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="notes",
        ),
    ]
