# Generated by Django 6.0.2 on 2026-03-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipping_price",
                    models.DecimalField(decimal_places=2, default=4.0, max_digits=6),
                ),
                (
                    "tax_percent",
                    models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
                ),
            ],
        ),
    ]
