# Generated by Django 6.0.2 on 2026-02-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="details_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
