# Generated by Django 6.0.2 on 2026-02-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_details_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="details_json",
        ),
        migrations.AddField(
            model_name="product",
            name="highlights",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="included",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="specs",
            field=models.TextField(blank=True),
        ),
    ]
