# Generated by Django 6.0.2 on 2026-03-29 13:04

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_details_json_product_highlights_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=catalog.models.product_image_path
            ),
        ),
    ]
